sudo: false
language: cpp
compiler:
  - clang
  - gcc
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://apt.llvm.org/zesty/ llvm-toolchain-zesty-4.0 main'
      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - gcc-7
    - clang-4.0
