sudo: false
language: cpp
compiler:
  - clang
  - gcc
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-zesty-4.0
    packages:
    - gcc-7
    - clang-4.0
